version: '3.8'
services:
  work_tracker_db:
    container_name: work_tracker_db
    image: postgres:14.1-alpine
    restart: always
    env_file:
    - .env
    ports:
      - '5432:5432'
    volumes:
      - ./.db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  work_tracker_api:
    container_name: work_tracker_api
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file:
    - .env
    depends_on:
      work_tracker_db:
        condition: service_healthy